### ISSUE TITLE
Upgrade DataDraw.disp()

### ISSUE THREAD

**Issue by KonradAdamek** [kmisztal/CEC#15]
Klasa nie współpracuje z nową wersją gral-core 0.11. Poprzednia wersja 0.10 nie jest dostępna w repozytoriach mavena.

**Comment by kmisztal** [comment]
Tą bibliotekę można usunąć, osoba robiąca zadanie #12 zajmie się tym

**Comment by kmisztal** [comment]
zadanie przerzucone na inne osoby i inne zadania
