### ISSUE TITLE
Inspekcja kodu

### ISSUE THREAD

**Issue by kmisztal** [kmisztal/CEC#9]

**Comment by KonradAdamek** [comment]
1. Pobierz: http://findbugs.sourceforge.net/
2. Przeskanuj projekt.
3. Napraw.
4. ???
5. Profitt.

**Comment by zdomcia** [comment]
jeżeli task jeszcze wolny to mogę spróbować się tym zająć

**Comment by kmisztal** [comment]
ok, proszę się tym zająć
